eukarya-inc/reearth-plateauview

plugin/web/components/common/Icon/icons.ts
plugin/web/components/sidebar/tabs/InfoTab.tsx

The info page didn't work fine 
When changing the name of the icon , I forgot to change it in the file "icons.ts" , so this pr is to fix that

fix: fix Info page

---

plugin/web/extensions/sidebar/modals/datacatalog/components/content/DatasetsPage/DatasetTree/FileTree.tsx
plugin/web/extensions/sidebar/modals/datacatalog/components/content/DatasetsPage/index.tsx

Done:
- Add add-button in to file-tree in data catalog's dataset tab
- Move addDisabled into a variable
Not done yet:
- Add functionality to add-button in file-tree in data catalog's dataset tab

feat(plugin): add add-button to file-tree

---

plugin/web/extensions/sidebar/modals/datacatalog/components/content/DatasetsPage/DatasetTree/FileTree.tsx

Done:
- Fix file-tree vertical scroll

style(plugin): fix file-tree scroll

---

plugin/web/extensions/sidebar/core/components/Desktop.tsx
plugin/web/extensions/sidebar/core/components/content/common/AddButton.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/general/Description.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/general/Legend.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/index.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/point/PointColor.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/types.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/index.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/hooks.ts
plugin/web/extensions/sidebar/core/components/hooks.ts
plugin/web/extensions/sidebar/popups/mobileDropdown/index.tsx

Includes wip point color field component

fix(plugin): field updating

---

plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/general/ButtonLink.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/index.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/types.ts

implement the field component Button Link
Design Link : https://www.figma.com/file/xWM8xrtIAh5oMj0seLd9Jd/view-2.0?node-id=2415%3A82836

feat(plugin): add button link field component

---

plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/general/ButtonLink.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/index.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/index.tsx

Also add pre-expanding to data card and field components

fix(plugin): button link

---

plugin/web/extensions/sidebar/modals/datacatalog/api/api.ts
plugin/web/extensions/sidebar/modals/datacatalog/components/content/DatasetDetails.tsx

Done:
- Fix search box
- Hide share button

fix(plugin): fix search box + hide share button

---

plugin/public/reearth.yml
plugin/src/sidebar.ts
plugin/web/extensions/sidebar/core/components/Desktop.tsx
plugin/web/extensions/sidebar/core/components/content/Selection/index.tsx
plugin/web/extensions/sidebar/core/components/content/Share/hooks.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/point/PointIcon.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/types.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/index.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/hooks.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/index.tsx
plugin/web/extensions/sidebar/core/components/hooks.ts
plugin/web/extensions/sidebar/core/types.ts
plugin/web/extensions/sidebar/modals/datacatalog/api/api.test.ts
plugin/web/extensions/sidebar/modals/datacatalog/api/api.ts
plugin/web/extensions/sidebar/modals/datacatalog/components/content/DatasetDetails.tsx
plugin/web/extensions/sidebar/modals/datacatalog/components/content/DatasetsPage/DatasetTree/File.tsx
plugin/web/extensions/sidebar/modals/datacatalog/components/content/DatasetsPage/DatasetTree/FileTree.tsx
plugin/web/extensions/sidebar/modals/datacatalog/components/content/DatasetsPage/Details.tsx
plugin/web/extensions/sidebar/modals/datacatalog/components/content/DatasetsPage/index.tsx
plugin/web/extensions/sidebar/modals/datacatalog/components/hooks.ts
plugin/web/extensions/sidebar/popups/mobileDropdown/Catalog/index.tsx
plugin/web/extensions/sidebar/popups/mobileDropdown/Selection/index.tsx
plugin/web/extensions/sidebar/popups/mobileDropdown/index.tsx
plugin/web/extensions/sidebar/types.ts

- Add camera position to saved project
- Add flyTo functionality to datacard's camera component

feat(plugin): camera functionality

---

plugin/web/extensions/geolocation/core/index.html
plugin/web/extensions/geolocation/core/index.tsx

Tiny PR to update the UI of my location widget as a round icon.

style(plugin): update my location UI

---

plugin/src/sidebar.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/index.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/index.tsx
plugin/web/extensions/sidebar/modals/datacatalog/components/content/DatasetsPage/DatasetTree/File.tsx

Also includes 
- a UI bug fix in datacatalog
- use reearth.layers.delete instead of ...hide

feat(plugin): Default template support

---

plugin/src/sidebar.ts
plugin/src/utils/csv.test.ts
plugin/src/utils/csv.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/general/Timeline.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/index.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/point/PointCSV.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/types.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/fieldHooks.ts
plugin/web/extensions/sidebar/types.ts

feat(plugin): support csv field

---

plugin/src/sidebar.ts
plugin/web/extensions/sidebar/core/components/Footer.tsx
plugin/web/extensions/sidebar/core/components/content/Selection/index.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/index.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/index.tsx
plugin/web/extensions/sidebar/core/components/hooks.ts
plugin/web/extensions/sidebar/modals/datacatalog/components/content/DatasetsPage/DatasetTree/TreeBuilder.tsx
plugin/web/extensions/sidebar/types.ts

Fix
- filetree file margin
- user-select none on much of the text
- hide default template in settings tab
- add open data url button if url available
- hide/show layer functionality added to eye icon
- only 3d tiles get an infobox with the PLATEAU infobox block

fix(plugin): various bugs and issues resolved

---

plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/index.tsx

Find search component from template.

fix(plugin): search button missing when set from template

---

plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/3dtiles/BuildingColor/hooks.ts

fix(plugin): flood rank field

---

plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/3dtiles/BuildingFilter/constants.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/3dtiles/BuildingFilter/hooks.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/3dtiles/BuildingFilter/index.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/3dtiles/BuildingFilter/useBuildingFilter.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/types.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/fieldHooks.ts

fix: building filter dynamically

---

plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/index.tsx

- Fix dataset's title with long file names

fix(plugin): dataset's title with long file names

---

plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/general/Description.tsx

Done:
- Fix description markdown's image size

fix(plugin): description markdown's image size

---

plugin/src/sidebar.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/3dtiles/BuildingColor/conditions.ts

fix: use color blend mode

---

plugin/web/extensions/sidebar/modals/datacatalog/components/content/DatasetDetails.tsx
plugin/web/sharedComponents/Popconfirm/index.tsx
plugin/web/sharedComponents/index.ts

Done:
- Add confirmation before publishing

feat(plugin): add confirmation before publishing

---

plugin/public/reearth.yml
plugin/src/sidebar.ts
plugin/web/extensions/sidebar/core/components/hooks.ts
plugin/web/extensions/sidebar/modals/datacatalog/api/api.ts

add sidebar settings to support multiple tennant for data catalog API

feat(plugin): settings of data catalog project id

---

plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/point/PointColor/index.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/point/PointStroke/index.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/polygon/PolygonColor/index.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/polygon/PolygonStroke/index.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/polyline/PolylineColor/index.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/types.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/common/ConditionField.tsx

I've updated the default value of the conditionField according to the following design

fix(plugin): change conditionField default Value

---

plugin/web/extensions/sidebar/core/components/hooks.ts
plugin/web/extensions/sidebar/modals/datacatalog/api/api.ts

Done:
- Change the name of usecase datasets use to be "zzz" instead of "xxx/yyy/zzz"

fix(plugin): usecase datasets' name

---

plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/index.tsx
plugin/web/extensions/sidebar/modals/datacatalog/api/api.ts
plugin/web/extensions/sidebar/modals/datacatalog/components/content/DatasetDetails.tsx
plugin/web/extensions/sidebar/modals/datacatalog/components/content/DatasetsPage/DatasetTree/File.tsx
plugin/web/extensions/sidebar/utils/file.ts

Done:
- Moved the logic the fix usecase datasets' name to file tree

refactor(plugin): usecase datasets' name

---

plugin/web/extensions/sidebar/core/components/Desktop.tsx
plugin/web/extensions/sidebar/core/components/content/Templates/index.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/general/Template.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/hooks.ts
plugin/web/extensions/sidebar/core/components/hooks.ts
plugin/web/extensions/sidebar/core/components/hooks/datasetHooks.ts
plugin/web/extensions/sidebar/core/components/hooks/index.ts
plugin/web/extensions/sidebar/core/components/hooks/projectHooks.ts
plugin/web/extensions/sidebar/core/components/hooks/templateHooks.ts
plugin/web/extensions/sidebar/core/components/hooks/utils.ts
plugin/web/extensions/sidebar/popups/mobileDropdown/index.tsx
plugin/web/extensions/sidebar/types.ts

Includes refactor for main sidebar hooks

fix(plugin): mobile not showing added datasets

---

plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/general/StyleCode/hooks.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/general/StyleCode/index.tsx

This PR uses component style code override.
Test project [here](https://test.reearth.dev/edit/01gty4xw1ysb8smcdycxp9qtm7).
Test shared project [here](https://test.reearth.dev/published.html?alias=ejdgeebgic). (建築物モデル（中央区)

fix(plugin): style code component

---

plugin/src/sidebar.ts

fix(plugin): use parameters in wms

---

plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/general/SwitchDataset/index.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/fieldHooks.ts
plugin/web/extensions/sidebar/core/components/hooks/utils.ts
plugin/web/extensions/sidebar/core/types.ts

- switch dataset's cleanse
- Don't save current show/hide state

fix(plugin): assortment of bugs

---

plugin/web/extensions/sidebar/modals/datacatalog/components/content/YourDataPage/WebDataTab.tsx
plugin/web/extensions/sidebar/modals/datacatalog/components/content/YourDataPage/WebFileTypeSelect.tsx

This PR resolve a BUG i observed while testing myData web data, Hopefully this fix resolves it.

fix(plugin): auto format detection in mydata web

---

plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/general/CurrentTime.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/general/Realtime.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/general/Timeline.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/point/PointCSV.tsx

I fixed to override layer at initial load on some field.

fix(plugin): initial onUpdate on some field

---

plugin/src/infobox.ts
plugin/src/sidebar.ts
plugin/web/extensions/infobox/core/components/common/PropertyBrowser.tsx
plugin/web/extensions/infobox/core/components/editPanel/index.tsx
plugin/web/extensions/infobox/core/components/viewPanel/index.tsx
plugin/web/extensions/infobox/core/hooks.ts
plugin/web/extensions/infobox/core/index.tsx
plugin/web/extensions/infobox/core/utils/index.ts
plugin/web/extensions/sidebar/core/components/hooks/templateHooks.ts
plugin/web/extensions/sidebar/core/types.ts

Supports different common properties for different data types.
Test project [here](https://test.reearth.dev/edit/01gsvnnzjawsjf6pjzt4cj262k).

fix(plugin): infobox show more common properties for data types

---

plugin/src/sidebar.ts

fix the clamp to ground property
- dataset for point testing: 関東地方整備局 河川ライブカメラ
- polygon test dataset: **行政界情報（東村山市）**
- Polyline test dataset : **交通情報**
- infobox: ランドマーク情報（千代田区）
- GTFS data : 西武バス バス関連リアルタイム情報
https://user-images.githubusercontent.com/89770889/224424293-04365ae7-aed9-4f7d-9e45-433a15632f78.mp4
https://user-images.githubusercontent.com/89770889/224424422-469cc302-bdc9-4ed3-a9c7-a2f259bc3129.mp4
https://user-images.githubusercontent.com/89770889/224424423-f1d8dc0c-f67a-4003-830f-c6eaae50f73b.mp4

fix(plugin) :  clamp to ground not working

---

plugin/web/extensions/sidebar/core/components/content/Templates/TemplateCard.tsx
plugin/web/extensions/sidebar/core/components/content/Templates/hooks.ts
plugin/web/extensions/sidebar/core/components/content/Templates/index.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/AccordionComponent.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/general/SwitchGroup/hooks.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/general/SwitchGroup/index.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/general/Template.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/types.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/fieldHooks.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/index.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/hooks.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/index.tsx
plugin/web/extensions/sidebar/core/components/hooks/projectHooks.ts
plugin/web/extensions/sidebar/core/components/hooks/utils.ts
plugin/web/extensions/sidebar/core/types.ts
plugin/web/extensions/sidebar/popups/groupSelect/index.tsx
plugin/web/extensions/sidebar/utils/dataset.ts
plugin/web/extensions/sidebar/utils/fieldGroups.ts

- Remove add/remove field groups on datasets
-  Hardcode 10 field groups
- Fix switch group handling (esp with templates)

feat(plugin): update switch group system

---

plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/3dtiles/BuildingColor/conditions.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/3dtiles/BuildingColor/constants.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/3dtiles/BuildingColor/hooks.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/3dtiles/BuildingColor/index.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/3dtiles/utils.ts

|急傾斜|土石流|地すべり|
|:--:|:--:|:--:|
|![Screen Shot 2023-03-13 at 17 01 37](https://user-images.githubusercontent.com/34934510/224651152-fb0620f4-0f92-4be5-86ad-105b68251915.png)|![Screen Shot 2023-03-13 at 17 01 18](https://user-images.githubusercontent.com/34934510/224651166-d4cb92fd-4e0e-42c9-98a7-e574f918d955.png)|![Screen Shot 2023-03-13 at 17 04 19](https://user-images.githubusercontent.com/34934510/224651182-e9e71c12-42f5-4ae1-b894-20b2b8972bf0.png)|
|![Screen Shot 2023-03-13 at 21 39 58](https://user-images.githubusercontent.com/34934510/224704963-ef9cb379-bac6-462c-ac3f-3fa219099a3a.png)|![Screen Shot 2023-03-13 at 21 36 52](https://user-images.githubusercontent.com/34934510/224704991-c14de49c-a72f-463a-b103-9872ba7b7064.png)|![Screen Shot 2023-03-13 at 21 41 …

fix(plugin): support colorizing landslide for 3dtiles

---

plugin/web/extensions/sidebar/core/components/Desktop.tsx
plugin/web/extensions/sidebar/core/components/content/Selection/index.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/index.tsx
plugin/web/extensions/sidebar/core/components/hooks/index.ts
plugin/web/extensions/sidebar/core/components/hooks/projectHooks.ts
plugin/web/extensions/sidebar/popups/mobileDropdown/Selection/index.tsx
plugin/web/extensions/sidebar/popups/mobileDropdown/index.tsx
plugin/web/sharedComponents/Icon/icons.ts
plugin/web/sharedComponents/Icon/index.tsx

Done:
- Add support for reordering datasets by adding drag and drop functionality

feat(plugin): datasets reordering by drag and drop

---

plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/index.tsx

This PR adds handle to dataset cards DnD.
https://user-images.githubusercontent.com/21994748/226232812-45dc5c84-9e67-4392-8a3d-6bfa0b7bc015.mp4

feat(plugin): dataset cards DnD with handle

---

plugin/src/sidebar.ts

This PR set `unselectOnClose` to `true` for infobox of all layers so that infobox can be fully hide when click close button.
Memo:
As far as i know all layers for plateauview project will have an infobox (using plugin block or builtin block from reearth).
If there's certain conditions that some layers should have no infobox, i'll change that merge to by condition.
https://user-images.githubusercontent.com/21994748/226828901-32f74657-18f7-4eb9-8c86-3a4e341c9346.mp4

feat(plugin): fully hide infobox when close

---

plugin/src/sidebar.ts
plugin/web/extensions/sidebar/core/components/hooks/index.ts
plugin/web/extensions/sidebar/modals/datacatalog/components/content/DatasetsPage/DatasetTree/index.tsx
plugin/web/extensions/sidebar/modals/datacatalog/components/content/DatasetsPage/index.tsx
plugin/web/extensions/sidebar/modals/datacatalog/components/hooks.ts
plugin/web/extensions/sidebar/modals/datacatalog/components/index.tsx
plugin/web/extensions/sidebar/popups/mobileDropdown/Catalog/index.tsx
plugin/web/extensions/sidebar/popups/mobileDropdown/index.tsx
plugin/web/extensions/sidebar/types.ts

Done:
-  Keep the search term even after closing the data catalog modal

feat(plugin): keep search term after closing modal

---

plugin/src/sidebar.ts

This PR fixes the issue observed while using polygon data on plugin. Somehow model defaults are causing this error which isn't directly connected models.

fix(plugin): cartographic dev error on polygon data

---

plugin/src/sidebar.ts

This PR refactor some on merge infobox global property.

refactor(plugin): merge infobox global property

---

plugin/src/sidebar.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/index.tsx
plugin/web/extensions/sidebar/types.ts

Done:
- Load mvt max zoom level from meta data.

feat(plugin): load mvt max zoom level from meta data

---

plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/index.tsx

Done:
- MVT camera doesn't move sometimes.

fix(plugin): mvt camera doesn't move sometimes

---

plugin/src/sidebar.ts
plugin/web/extensions/sidebar/core/components/hooks/projectHooks.ts

Default hide underground will cause other problems and we need to revert this for now.

fix(plugin): revert hide underground default to false

---

plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/general/CurrentTime.tsx

Done:
- Fix the bug when setting end time in the current time component causes the system to crash

fix(plugin): end time in current time component

---

plugin/src/sidebar.ts

Done:
- Fix mvt camera on mobile

fix(plugin): mvt camera on mobile

---

plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/general/LegendGradient/hooks.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/general/LegendGradient/index.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/index.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/types.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/fieldHooks.ts

Add the field component (legend gradient)
test project (temp link ) :https://test.reearth.dev/edit/01gw4bkn0p6qq9egkvv4kx6nvf

feat(plugin): add legend gradient field component

---

plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/index.tsx

Handle promise error so that won't stuck progress.

fix(plugin): handle fetch mvt position error

---

plugin/src/sidebar.ts
plugin/web/extensions/infobox/core/utils/attributes.ts

This PR adds support for type `rail` (鉄道モデル) on infobox.

feat(plugin): infobox support type rail 

---

plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/3dtiles/BuildingFilter/constants.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/3dtiles/BuildingFilter/hooks.ts

Description:
- Fix minimum age value for building filter.

fix(plugin): minimum age value for building filter

---

plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/3dtiles/BuildingFilter/constants.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/3dtiles/BuildingFilter/useBuildingFilter.ts

This PR updates the min val behaviour policy for building filter and update BuildingAge Min Value.

fix(plugin): min val policy update for building filter 

---

plugin/src/sidebar.ts
plugin/web/extensions/sidebar/core/components/desktop/hooks/datasetHooks.ts
plugin/web/extensions/sidebar/core/components/desktop/hooks/index.ts
plugin/web/extensions/sidebar/core/components/desktop/hooks/projectHooks.ts
plugin/web/extensions/sidebar/core/components/mobile/hooks/index.ts
plugin/web/extensions/sidebar/core/components/mobile/hooks/projectHooks.ts
plugin/web/extensions/sidebar/core/components/mobile/index.tsx
plugin/web/extensions/sidebar/modals/datacatalog/components/content/DatasetsPage/DatasetTree/index.tsx
plugin/web/extensions/sidebar/modals/datacatalog/components/hooks.ts
plugin/web/extensions/sidebar/popups/mobileDropdown/Catalog/index.tsx
plugin/web/extensions/sidebar/popups/mobileDropdown/index.tsx

The slow startup of the sidebar and lag in the scene on page load was due to the processing of the catalog happening twice, as well as the very large processedCatalog being sent through the API.
This PR
- Makes sure the catalog processing happens only once after the catalog and data are both fetched
- Moves the catalog and as much of its logic as possible in to the modal (this does me we fetch the catalog and process EVERY time the modal opens, but this is faster than through the API and also means we get an up-to-date catalog, removing the need to worry about old state somewhere in the plugin.)

perf(plugin): slow startup

---

plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/general/SwitchDataset/index.tsx

Remove space on type string for update switch dataset value.

fix(plugin): some 3d tiles not showing when switch dataset

---

plugin/web/extensions/sidebar/modals/datacatalog/components/hooks.ts

Before: we were refetching Data
Now: we are updating component state rather than refetching

perf(plugin): speed up publishing/unpublishing datasets

---

plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/index.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/polygon/PolygonClassificationType/index.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/polyline/PolylineClassificationType/index.tsx
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/types.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/fieldConstants.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/fieldHooks.ts

This PR adds two new field components: 
`PolylineClassificationType` `PolygonClassificationType`
https://user-images.githubusercontent.com/21994748/229477773-aebc473f-9ce0-4916-b5f2-96302e312fe8.mp4

feat(plugin): add field component polyline polygon classification type

---

plugin/src/sidebar.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/3dtiles/Clipping/useClippingBox.ts
plugin/web/extensions/sidebar/types.ts

We can't use window.parent in plugins, so fixed this part

fix(plugin): remove trying to access window.parent in clipping box field

---

plugin/web/extensions/sidebar/core/components/desktop/hooks/projectHooks.ts
plugin/web/extensions/sidebar/core/components/mobile/hooks/projectHooks.ts

Condition for checking user story in shared project was incorrect.

fix(plugin): story telling share not working

---

plugin/src/sidebar.ts
plugin/web/extensions/sidebar/core/components/desktop/hooks/projectHooks.ts
plugin/web/extensions/sidebar/core/components/mobile/hooks/projectHooks.ts

Set `allowEnterGround` default as `true`.

fix(plugin): set allow enter ground default as true

---

plugin/web/extensions/sidebar/modals/datacatalog/components/hooks.ts

When publish a new dataset the new dataset does not been added to `data`, which make the UI does not update.

fix(plugin): publish new dataset does not update data

---

plugin/src/pedestrian.ts
plugin/web/extensions/pedestrian/popups/pedestrianController/components/ControlButton/index.tsx
plugin/web/extensions/pedestrian/popups/pedestrianController/components/hooks.ts
plugin/web/extensions/pedestrian/popups/pedestrianController/components/index.css
plugin/web/extensions/pedestrian/popups/pedestrianController/components/index.tsx
plugin/web/extensions/pedestrian/types.ts

Update pedestrian:
- Redesign speed solution, add speed button 1x, 2x, 3x.
- Add zoom control to minimap.
Test project [here](https://test.reearth.dev/edit/01h028h747ez2fq6bwtf7pp9fs).

refactor(plugin): pedestrian UI/UX update

---

.github/labeler.yml
.github/workflows/ci-plugin-version-update.yml
.github/workflows/ci.yml
.github/workflows/pr-title.yml

This PR adds support for automatic update of plugin version and PR title check workflow.

ci: support auto plugin version update and pr title check

---

.github/workflows/ci-plugin-version-update.yml

This reverts commit 80bb292c91d06c2f5b784667b174f555bc82fd42.

ci: revert refactor plugin-version-update(minor) (#440)

---

plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/hooks.ts
plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/index.tsx

This PR fix the  plateau template shows in custom dataset field component unexpectly.
Test project [here](https://test.reearth.dev/edit/01h1jgk248aby5r4rxkxm7g0jg).

fix(web): plateau template shows in custom dataset field component unexpectly (major)

---

plugin/src/pedestrian.ts
plugin/src/sidebar.ts
plugin/src/storytelling.ts

Need to check the `themeType` since the `themeSelectColor` persists even the `themeType` is not `custom`.
Test project [here](https://test.reearth.dev/edit/01h1jgk248aby5r4rxkxm7g0jg).

fix(plugin): check themeType when set custom theme color (major)

---

terraform/modules/cms/cloudrun-cms-worker.tf
terraform/modules/cms/cloudrun-cms.tf
terraform/modules/cms/cloudrun-plateau.tf
terraform/modules/cms/cloutask.tf
terraform/modules/cms/iam.tf
terraform/modules/reearth/cloudrun.tf

added permission for cloudbuild to IAM role for cms

fix(terraform): fix project ID, add cloudbuild.create permission

---

plugin/public/reearth.yml
plugin/src/sidebar.ts

Add a setting to widget property to disable welcome page.

feat(plugin): widget property to disable welcome page

---

plugin/src/sidebar.ts
plugin/web/extensions/infobox/core/utils/attributes.ts

Add support of type `brid` for infobox.

feat(plugin): support type brid

---

plugin/src/sidebar.ts
plugin/web/extensions/infobox/core/utils/attributes.ts

Add new type `cons` `wwy` `area`.

feat(plugin): new types support for infobox

---

.vscode/settings.json
plugin/web/extensions/sidebar/modals/datacatalog/api/api.ts
plugin/web/extensions/sidebar/modals/datacatalog/api/path.test.ts
plugin/web/extensions/sidebar/modals/datacatalog/api/path.ts
plugin/web/extensions/sidebar/modals/datacatalog/api/sort.test.ts
plugin/web/extensions/sidebar/modals/datacatalog/api/sort.ts
server/datacatalog/.gitignore
server/datacatalog/datacatalogutil/common.go
server/datacatalog/echo_test.go
server/datacatalog/fetcher.go
server/datacatalog/fetcher_test.go
server/datacatalog/item.go
server/datacatalog/item_dataset.go
server/datacatalog/item_dataset_test.go
server/datacatalog/item_plateu.go
server/datacatalog/item_usecase.go
server/datacatalog/item_usecase_test.go
server/datacatalog/plateauv2/builder.go
server/datacatalog/plateauv2/dataset.go
server/datacatalog/plateauv2/dataset_test.go
server/datacatalog/plateauv2/feature.go
server/datacatalog/plateauv2/feature_test.go
server/datacatalog/plateauv2/item.go
server/datacatalog/util.go

Allow the creation of root folders other than "ユースケース" in the data catalog.

feat: data catalog category

---

plugin/web/extensions/sidebar/core/components/desktop/hooks/index.ts
plugin/web/extensions/sidebar/core/components/desktop/hooks/projectHooks.ts

Sidebar init is async and it could happen after update project with draftProject defined in projectHooks (which doesn't take scene camera property).
Init updateProject should also trigger a updateProject action just like it been used in other places.

fix(plugin): initial camera position

---

plugin/web/extensions/sidebar/core/components/content/common/FieldComponent/Fields/3dtiles/BuildingFilter/constants.ts

This PR update range max to 100 for building filter of property abovegroundFloor

refactor(plugin): update max aboveground floor value for building filter

---

plugin/web/extensions/sidebar/core/components/content/MapSettings/hooks.ts
plugin/web/extensions/sidebar/core/components/content/MapSettings/types.ts

fix(plugin): remove bing and dark-matter base-map
