eukarya-inc/reearth-plateauview

- plugin/web/components/common/Icon/icons.ts
- plugin/web/components/sidebar/Layout/LayoutContent.tsx
- plugin/web/components/sidebar/tabs/MapSettingTab.tsx
The main purpose is to create plugins that shows plateau view functionalities, and one of them map setting 
please refer to this https://github.com/eukarya-inc/reearth-plateauview/issues/25
1. create the map setting page
> feat: create Map setting page for plateau view 

- plugin/web/extensions/sidebar/modals/datacatalog/components/content/DatasetDetails.tsx
Done:
- Add publish button to data catalog's dataset tab
- Refactor styled components
Not done yet:
- Add functionality to publish button in data catalog's dataset tab
> feat(plugin): add publish button to data catalog

- plugin/src/sidebar.ts
- plugin/web/extensions/sidebar/core/components/hooks.ts
- plugin/web/extensions/storytelling/core/hooks.ts
- plugin/web/extensions/storytelling/modals/sceneEditor/components/hooks.ts
- plugin/web/extensions/storytelling/modals/sceneEditor/components/index.tsx
- plugin/web/extensions/storytelling/types.ts
This is a small PR update some behaviors about story telling:
- Forbidden scene save with empty title.
- Create new scene after save scene info.
- Save story on every edit of scenes. Share only set sidebar to share page.
Tested with [this project.](https://test.reearth.dev/edit/01gpmnf4ah0syavpemp8ywhhsf)
> feat(plugin): story telling behavior updates

- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/point/PointColor.tsx
- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/point/PointColorItem.tsx
- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/point/PointStroke.tsx
- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/point/PointStrokeItem.tsx
- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/point/common/ColorField.tsx
- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/point/common/ConditionField.tsx
- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/point/common/NumberField.tsx
- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/point/common/index.ts
- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/point/commonComponents/index.ts
- plugin/web/extensions/sidebar/utils/index.ts
- plugin/web/sharedComponents/InputNumber/index.tsx
- plugin/web/sharedComponents/index.ts
Done:
- Implement up and down functionality for `PointColor` and `PointStroke`
- Keep state for common components
- Add `swap`, `moveItemUp`, `moveItemDown` and `removeItem` methods into `util.js`
> fix(plugin): field's move up down functionality

- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/index.tsx
When scroll bar shows on sidebar, the database card arrow not locate corretly.
Before:
After:
> fix(plugin): position error of dataset card arrow

- plugin/web/extensions/sidebar/core/components/content/Templates/TemplateCard.tsx
- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/AddButton.tsx
- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/3dtiles/BuildingShadow/index.tsx
- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/3dtiles/Clipping/index.tsx
- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/general/Legend/index.tsx
- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/general/SwitchDataset/index.tsx
- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/general/SwitchGroup/index.tsx
- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/common/ConditionField.tsx
- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/commonComponents/index.ts
- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/index.tsx
- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/index.tsx
- plugin/web/extensions/sidebar/popups/buildingSearch/components/ConditionPanel/Condition.tsx
- plugin/web/extensions/storytelling/core/components/editor/scene.tsx
We need to make all dropdown & select follow scroll when scrolling, so please notice when using ANTD `Dropdown` & `Selcet`:
- Add `getPopupContainer={trigger => trigger.parentElement ?? document.body}` to `Dropdown` or `Select`.
- Make sure the tirgger element has a close parent(with in scroll content) with css property`position` setted.
> fix(plugin): dropdown / select position fixed when outer scrolling

- plugin/web/extensions/sidebar/modals/datacatalog/index.html
Fix the scrollbar for the datacatalog modal for Windows users
> fix(plugin): scrollbar in Data Catalog modal always shows for windows users 

- plugin/src/sidebar.ts
- plugin/web/extensions/sidebar/core/components/content/Share/hooks.ts
`?share=xxx` is simpler and easier to understand that the URL is intended to be shared than `?projectID=xxx`
> fix(plugin): change query name for share URL

- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/index.tsx
Done:
- For the field component names, the added (一般) part should be viewable only in the edit tab 設定 not in the public tab 公開.
> fix(plugin): field component name for public and edit mode

- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/hooks.ts
This PR connects filed component style code with the functionality.
[Test project](https://test.reearth.dev/edit/01gtxp0y9ee6wx73wbt9k5qp9n)
To test import 避難施設情報（千代田区）
It has 2 groups each group with 2 explanation components, and one explanation component not belonging to any of the two.
also, it has a switch group component, that contains both group 1 and group 2.
The component which does not belong to any group should be always visible.
a1, b1 => group 1
a2, b2 => group 2
c (no group)
settings: 
public:
> fix(plugin): show components not belonging in groups 

- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/general/Realtime.tsx
The parseInt function used in the `handleChangeUpdateTime` callback expects a string argument, but when the text field is empty, it returns `NaN `which causes the state to be set to `NaN` as well.
> fix(plugin): when the number is deleted it shows a "NaN"

- plugin/src/sidebar.ts
Sidebar uses `gml_id` for color expression to highlight the selected feature.
Use case 3d tiles does not have `gml_id` cause it cannot get highlighted.
Update with using fearture id instead of `gml_id` so that all 3d tiles feature can be highlighted.
Memo: NLS supports using feature id in condition expressions.
https://user-images.githubusercontent.com/21994748/224665897-a2362b05-c64e-4a42-9a82-cdc8de56f028.mp4
> fix(plugin): 3d tiles from use case cannot get highlighted when select

- plugin/src/sidebar.ts
This PR caused the `避難施設情報 data and ランドマーク情報 can not bee seen anymore …` BUG.
> Revert "fix(plugin) :  clamp to ground not working"

- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/general/Template.tsx
- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/hooks.ts
- plugin/web/extensions/sidebar/utils/dataset.ts
What i did in this PR:
- `getActiveFieldIDs` now take templates in compute. Before this PR when a dataset which conatins a template added, it can't get the components inside the template (template's components are not saved to backend).
- If there's a template exists, always filter from all template component when switch group.
> fix(plugin): use template does not work

- plugin/web/extensions/sidebar/core/components/content/Feedback/hooks.test.ts
- plugin/web/extensions/sidebar/core/components/content/Feedback/hooks.ts
Fix send feedback with image since it sent dataurl
I've tested by installing this plugin and send feedback. This is an email I've recieved
> fix(plugin): send feedback with image

- plugin/web/extensions/sidebar/core/components/hooks/projectHooks.ts
Done:
- This PR fixes what has been done in the drag and drop PR that removed the `.reverse()` statement from the `selectedDatasets?.map()` statement in `@web/extensions/sidebar/core/components/content/Selection/index.tsx` file.
- Before: newly added dataset's position is last.
- After: newly added dataset's position is first.
> fix(plugin): newly added dataset position

- plugin/src/sidebar.ts
TerriaJS sets default alpha as 0.8 and 1.1 uses it, so we can set default alpha 0.8.
> fix(plugin): set alpha for wms

- plugin/src/infobox.ts
Check selectedFeature id to avoid fetch twice.
https://user-images.githubusercontent.com/21994748/227243605-d68a34f7-247a-45da-a90a-62143cb2f375.mp4
For now i don't know why this `on select` will trigger twice on each click on building.
> fix(plugin): infobox update twice on each click

- plugin/src/sidebar.ts
- plugin/web/extensions/sidebar/core/components/hooks/projectHooks.ts
Option `地下を隠す` should be enabled by default.
https://user-images.githubusercontent.com/21994748/227404083-ed2adc67-6996-4d04-aae7-89a6cf1c7e09.mp4
> fix(plugin): enable hide underground by default

- plugin/src/sidebar.ts
- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/index.tsx
MVT layer needs to get center location by request metadata which use postMessage to transfer data. If it can't get the correct layer data the flyTo can't work.
The event listener expect to receive the exact match result postMessage but actully it can't at most of time since:
- There might be other message transfer at almost the same time, since it's async it's not reliable.
- When `Selection` tab become active, all datasets card got enabled there might be multiple request sent. The results could be matched wrong.
- Add dataID to match the layer data and the dataset data.
- Add a timeout.
https://user-images.githubusercontent.com/21994748/227695747-a2270f94-39b6-4339-9e8a-5e4c091fb1cd.mp4
> fix(plugin): mvt flyTo only works for the first entry

- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/general/CurrentTime.tsx
- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/general/Template.tsx
- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/index.tsx
Done:
- Fixed the bug when current time inside templates doesn't work and cause the system to crash.
How to test:
- Add any dataset
- create a template with two current time component each belongs to a different group
- add a switch group to the template
- try to switch between the two groups
> fix(plugin): current time inside templates doesn't work

- plugin/src/sidebar.ts
- plugin/web/extensions/sidebar/core/components/content/MapSettings/hooks.ts
- plugin/web/extensions/sidebar/core/components/content/MapSettings/index.tsx
- plugin/web/extensions/sidebar/core/components/hooks/projectHooks.ts
- plugin/web/extensions/sidebar/types.ts
This PR add option `太陽光を利用する` to map settings. Default as unchecked.
- When checked use scene light: sunLight
- When unchecked use scene light: directionalLight
https://user-images.githubusercontent.com/21994748/227726317-f148f83f-0cbc-46dc-a728-3397975ff616.mp4
> feat(plugin): add use sunlight option

- plugin/web/extensions/infobox/core/hooks.ts
- plugin/web/extensions/infobox/core/utils/attributes.ts
The `name` property for `htd` is defined as `name`. When `getRootFields` it uses `名称`(which is good for buildings) so that there become two `name`s.
> fix(plugin): same property `名称` displayed on infobox of htd

- plugin/web/extensions/sidebar/core/components/hooks/utils.ts
cleanseOverride.data.url with switchDataset is undefined sometimes. Initial url of dataset is overridden with undefined, so some dataset is not working correctly.
I fixed to prevent overriding with undefined `cleanseOverride.data.url`.
> fix(plugin): prevent override data url with undefined

- plugin/src/sidebar.ts
- plugin/web/extensions/sidebar/modals/datacatalog/components/content/DatasetsPage/index.tsx
- plugin/web/extensions/sidebar/popups/buildingSearch/components/ConditionPanel/index.tsx
- plugin/web/extensions/sidebar/popups/buildingSearch/components/hooks.ts
Building search result's height does not consider terrain therefore the lookAt target will be incorrect.
This PR fix:
- lookAt with sampleTerrainHeight added. (require PR merged on reearth)
- Hide search conditions that has no value.
- When search result has multiple items, camera no longer fly to the first result (keep the same behavior as v1.1)
https://user-images.githubusercontent.com/21994748/227793496-e036cca0-5599-4d98-9e2b-b9583b677a68.mp4
> fix(plugin): building search lookAt with terriain height

- plugin/web/extensions/sidebar/modals/welcomescreen/index.tsx
The close button of welcome screen is pushed off the screen in certain phone, this pr is to fix that.
- Add a new style rule for the InnerWrapper to set a max-width property.
- Update the style rule for the WelcomeCloseButton to use flex-grow instead of a fixed width.
This will allow the button to scale with flex and prevent it from being pushed off the screen at certain phone
> fix(plugin):the close button of welcome screen is pushed off the screen in certain phone

- plugin/web/extensions/sidebar/core/components/utils.ts
`ProcessOverrides` sends in the components that can potentially affect the styling, while It wasn't visible with normal data which doesn't have style code. The order of applying overrides doesn't work in the case of style code because the components also contains a `group` of style code which has the original style.
You can think of component in the code syle-code as collection of original and updated style which comes from transparency change and while merging these styles, till now we were consider the updates before than the original style merge. which should be opposite.
> fix(plugin): transparency with style code doesn't work

- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/3dtiles/BuildingTransparency/useBuildingTransparency.ts
- plugin/web/extensions/sidebar/core/components/utils.ts
- plugin/web/extensions/sidebar/utils/color.ts
This PR is a temporary fix for a problem observed with transparency of `3dtiles` with when switch group and style code exist. It also fixes bugs caused by https://github.com/eukarya-inc/reearth-plateauview/pull/370
> fix(plugin): transparency with switch groups with style code

- plugin/web/extensions/sidebar/utils/color.ts
This small PR adds an exception to onclick highlighting condition while changing the transparency for layer.
> fix(plugin): add exception to highlight with transparency

- plugin/web/extensions/sidebar/utils/color.ts
This PR adds support for `color(hexcode)` compatible for transparency.
> feat(plugin): support color string for styling with transparency

- plugin/web/extensions/sidebar/modals/datacatalog/components/content/DatasetsPage/Details.tsx
- plugin/web/extensions/sidebar/modals/datacatalog/components/content/DatasetsPage/index.tsx
Done:
- fix: a city is selected by default when data catalog was opened in editor
> fix(plugin): remove default selected city when opening data catalog

- plugin/src/sidebar.ts
- plugin/web/extensions/sidebar/modals/datacatalog/api/api.ts
This PR adds support for data catalog data type:
```ts
{
...rest,
layers?: string | string[],
layer?: string | string[],
config?: {
data?: {
...data,
layer?: string | string[],
layers?: string | string[], 
}
}
}
```
> fix(plugin): data url layers not match

- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/general/Legend/index.tsx
- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/general/LegendGradient/index.tsx
- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/general/SwitchDataset/index.tsx
- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/general/SwitchGroup/index.tsx
Set CSS style font size to 0 for dropdown icons to aviod the line height effects vertical alignment.
Fixes dropdown arrows in `switchDataset` `switchGroup` `legend` `legendGradient`
BEFORE:
AFTER:
> fix(plugin): some dropdown arrows are not vertical aligned

- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/Field/Fields/general/SwitchVisibility/index.tsx
- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/hooks.ts
The selection state of reearth will not be changed when user switch group or switch dataset. 
The previously selected entity might not be exists any more after the switch but if there was an infobox displayed the infobox will stay there.
Reorder the action in switchVisibility as well.
https://user-images.githubusercontent.com/21994748/229417297-c5327ae8-4bdc-4c3f-8883-203a3b0b5d31.mp4
> fix(plugin): unselect when switch current group or dataset

- plugin/web/extensions/sidebar/core/components/content/common/DatasetCard/hooks.ts
- plugin/web/extensions/sidebar/core/components/content/common/FieldComponent/Fields/3dtiles/BuildingColor/hooks.ts
- plugin/web/extensions/sidebar/core/components/content/common/FieldComponent/Fields/3dtiles/BuildingColor/index.tsx
- plugin/web/extensions/sidebar/core/components/content/common/FieldComponent/Fields/3dtiles/BuildingFilter/useBuildingFilter.ts
- plugin/web/extensions/sidebar/core/components/content/common/FieldComponent/Fields/3dtiles/BuildingShadow/useBuildingShadow.ts
- plugin/web/extensions/sidebar/core/components/content/common/FieldComponent/Fields/3dtiles/Clipping/useClippingBox.ts
- plugin/web/extensions/sidebar/core/components/content/common/FieldComponent/Fields/3dtiles/hooks.ts
- plugin/web/extensions/sidebar/core/components/content/common/FieldComponent/Fields/general/SwitchDataset/index.tsx
- plugin/web/extensions/sidebar/core/components/content/common/FieldComponent/Fields/general/Template.tsx
- plugin/web/extensions/sidebar/core/components/mobile/hooks/index.ts
- plugin/web/extensions/sidebar/popups/mobileDropdown/index.tsx
- plugin/web/extensions/sidebar/utils/overrides.ts
- Fix some filed component value can't be applied, or enter an apply-reset loop:
When on mobile, the `project` is not synced. Therefore the update of components can't get the updated values, when multiple filed components update triggerred, the out-of-date value could be carried and override the previous update.
- Fix infinite update:
switchDataset use `===` to check two objects, which could lead to infinite loop update.
- Fix overrides happen when initialization for `BuildingColor` `BuildingFilter` `BuildingShadow` `Clipping`.
- Fix override sort for `updateAt`, it could be string.
- Fix data catalog can't fetch data on switch tab.
- Fix an CSS property error.
- Fix mobile build search use wrong id.
Test project [here](https://test.reearth.dev/edit/01gxns5mw9axjt9q3sc2fajfnh).
> fix(plugin): infinite loop on mobile

- plugin/web/extensions/sidebar/popups/buildingSearch/components/hooks.ts
- plugin/web/extensions/sidebar/popups/buildingSearch/components/index.tsx
Small changes on building search to optimize UX:
- Always fly to the first result to make sure there's result shown in viewport.
- Make minipanel clickable.
> feat(plugin): building search always fly to the first match result

- plugin/web/extensions/sidebar/modals/datacatalog/components/content/DatasetsPage/DatasetTree/Folder.tsx
When opening datacatalog folder and open dataset page ,if the folder name is very long we need to wrpe in multiple lines
test project : https://test.reearth.dev/edit/01gya8qmmaj6qzj1qksg6nf20x
> fix(plugin): wrap the long titles for folders in datacatalog modal

- plugin/web/extensions/sidebar/popups/help/BasicOperation/index.tsx
サイドメニューの「使い方」→「基本操作」にある説明ですが、誤字があるように思いました！
当PRで、3箇所の微修正を行なっています。
重複: [Fix typos: "トラッグ" → "ドラッグ" by sorami · Pull Request #1 · Project-PLATEAU/PLATEAU-VIEW-2.0](https://github.com/Project-PLATEAU/PLATEAU-VIEW-2.0/pull/1)
> Fix typos: "トラッグ" → "ドラッグ"

- plugin/src/sidebar.ts
- plugin/web/extensions/sidebar/core/components/desktop/hooks/projectHooks.ts
This PR fix:
1. Correct shared project's datasets' visibility.
2. Reverse shared project's datasets' order.
> fix(plugin): incorrect visibility and order of shared project's datasets

- plugin/web/extensions/sidebar/modals/datacatalog/api/api.ts
- plugin/web/extensions/sidebar/modals/datacatalog/api/utils.ts
This PR shows the catalog description correctly.
I modified the folder description retrieval in `plugin/web/extensions/sidebar/modals/datacatalog/api/utils.ts` to ensure accurate descriptions are used when generating the tree.
I have tested the changes by generating the data catalog tree and confirming that the folder descriptions are now correctly displayed. Additionally, I have tested with UI here [Test project](https://test.reearth.dev/edit/01gx0yyj0qt4p4wpmhzd6gs1b7) making sure the right description is shown.
> fix(plugin): show catalog description

- plugin/src/sidebar.ts
- plugin/web/extensions/sidebar/core/components/desktop/hooks/projectHooks.ts
- plugin/web/extensions/sidebar/core/types.ts
- plugin/web/extensions/sidebar/modals/datacatalog/components/content/YourDataPage/LocalDataTab.tsx
- plugin/web/extensions/sidebar/modals/datacatalog/components/content/YourDataPage/WebDataTab.tsx
- plugin/web/extensions/sidebar/modals/datacatalog/components/content/YourDataPage/utils.ts
- plugin/web/extensions/sidebar/modals/datacatalog/types.ts
When user using My Data to upload a local csv file or load from an online csv url:
- system should detect the lat/lng/height by col name.
- system should set a default marker appearance for csv items if valid position col been found.
Basically this feature will be used in published page.
- Find the position columes with hard coded keywords:
- latitude: `"latitude", "lat", "緯度", "北緯"`
- longitude: `"longitude", "lng", "lon", "経度", "東経"`
- height: `"height", "altitude", "alt", "高度"`
- Add default marker appearnce if lat & lng exists.
- Add `additionalData` to dataset and set override when createLayer
- Modify the text on detail panel of Mydata.
- Fix fetching project sometimes fetch twice bug.
Test with [this](https://test.reearth.dev/edit/01gtk2bjcpy103bep25kj4a2ve) project.
> feat(plugin): detect position and set default marker for csv from my data

- plugin/src/infobox.ts
- plugin/web/extensions/infobox/core/components/editPanel/index.tsx
- plugin/web/extensions/infobox/core/hooks.ts
- plugin/web/extensions/infobox/core/index.tsx
- plugin/web/extensions/sidebar/core/components/desktop/hooks/projectHooks.ts
Dataset's `type` and `type_en` is no longer one-to-one pair from data. 
Perticually `type` 建築物モデル and 建築物・橋梁モデル share the same `type_en` as `bldg`.
Therefore we should use dataset's type name as the infobox title instead of the template name.
Note: `type_en` is the actual key for infobox field template.
Test project [here](https://test.reearth.dev/edit/01gtk2bjcpy103bep25kj4a2ve).
> feat(plugin): display type name as infobox title instead of template name 

- plugin/web/extensions/infobox/core/components/common/PropertyBrowser.tsx
- plugin/web/extensions/infobox/core/utils/clearfyDate.test.ts
- plugin/web/extensions/infobox/core/utils/clearfyDate.ts
- plugin/web/extensions/infobox/core/utils/index.ts
`0001-01-01` is used for present unknown in some attributes, we need to display `不明` instead of the dummy date.
Note: only replace `0001-01-01` for now, we should not replace the value too generic like `01` since it could be some meaningful value.
Before | After
----- | -----
Test project [here](https://test.reearth.dev/edit/01gtk2bjcpy103bep25kj4a2ve).
Test with these datasets:
- **区域区分モデル（横浜市）**
- **用途地域モデル（横浜市）**
> feat(plugin): replace unknown date in feature attributes

- plugin/web/extensions/sidebar/modals/datacatalog/components/content/DatasetsPage/Details.tsx
- plugin/web/extensions/sidebar/modals/datacatalog/components/content/DatasetsPage/index.tsx
- plugin/web/extensions/sidebar/popups/mobileDropdown/Catalog/index.tsx
Hide the g-space link from dataset detail page when it's a dataset of local city.
| Local dataset      | Plateau dataset |
| ----------- | ----------- |
| ![image](https://github.com/eukarya-inc/reearth-plateauview/assets/21994748/a22bc4c8-0b1d-46e1-b4fc-1acf45342bdf)      | ![image](https://github.com/eukarya-inc/reearth-plateauview/assets/21994748/d5dfc241-53e4-441a-b487-2b251ea0c567)       |
> feat(plugin): hide g-space link for datasets of local city

- plugin/src/sidebar.ts
- plugin/web/extensions/infobox/core/hooks.ts
- plugin/web/extensions/infobox/core/utils/attributes.ts
- Add a fallback `?? []` in case there's any new type that didn't exists in `commonPropertiesMap`.
- Add type support for `gen`
> fix(plugin): support datatype gen for infobox
